# frame size
n = 256
# maximum number of buffers in channel queue
max_buffers = 16

[uniforms]
decay = 0.5
thickness = 8.0
thinning = 1.0
base_hue = 0.3333
colorize = true

[debug]
# when buffers are dropped, print "!"
print_drop = true
