[audio]
buffer_size = 256
num_buffers = 16
fft_size = 2048

[uniforms]
decay = 0.5
thickness = 2.0
thinning = 0.0
base_hue = 0.3333
colorize = true

[debug]
# when buffers are dropped, print "!"
print_drop = true
